name: Release Samplr

on:
  push:
    tags:
      - 'v*'

permissions:
  # allow the workflow to get code and upload artifacts
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: build samplr binary
        run: cargo build --release
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: samplr-windows
          path: target/release/samplr.exe
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: samplr-linux
          path: target/release/samplr

  release:
    name: create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            :sparkles:
          draft: false
          prerelease: false

      - uses: actions/download-artifact@v2
        with:
          name: samplr-windows
          path: samplr-windows

      - uses: actions/download-artifact@v2
        with:
          name: samplr-linux
          path: samplr-linux

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            samplr-linux/samplr
            samplr-windows/samplr.exe
