name: Release Samplr

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: build samplr binary
        run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: samplr-${{ matrix.os }}
          path: target/release/samplr

  release:
    name: create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            :sparkles:
          draft: false
          prerelease: false

      - uses: actions/download-artifact@v2
        with:
          name: samplr-windows-latest

      - uses: actions/download-artifact@v2
        with:
          name: samplr-ubuntu-latest

      # to be continued...
